name: Release Bashbot
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Release Bashbot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Release Bashbot"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_APPNAME: ${{ secrets.REGISTRY_APPNAME }}
          FORK_OWNER: ${{ secrets.FORK_OWNER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          go build bashbot.go
          tag=$(git describe --tags)
          message="$(git for-each-ref refs/tags/$tag --format='%(contents)')"
          name=$(echo "$message" | head -n1)
          # Create a release
          release=$(curl -XPOST -H "Authorization:token $GIT_TOKEN" --data "{\"tag_name\": \"$tag\", \"target_commitish\": \"main\", \"name\": \"bashbot-${tag}\", \"body\": \"$name\", \"draft\": false, \"prerelease\": false}" https://api.github.com/repos/${FORK_OWNER}/bashbot/releases)
          echo "$release"
          echo "${tag}" > version
          rm -rf .git
          echo "$REGISTRY_PASSWORD" | docker login ${REGISTRY_URL} -u="$REGISTRY_USERNAME" --password-stdin
          docker build -t bashbot-local .
          docker tag bashbot-local ${REGISTRY_URL}/${REGISTRY_APPNAME}:${tag}
          docker push ${REGISTRY_URL}/${REGISTRY_APPNAME}:${tag}
          cd ..
          tar -zcvf bashbot.tar.gz bashbot
          mv bashbot.tar.gz bashbot/.
      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: bashbot.tar.gz
          path: bashbot.tar.gz
          
